version: '3.1'
services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    ports:
      - 8123:8123
    volumes:
      - ./configuration.yaml:/config/configuration.yaml
      - ./ui-lovelace.yaml:/config/ui-lovelace.yaml
      - ./dist/softphone-card.js:/config/www/softphone-card.js
