title: Softphone Card
views:
    # View tab title.
  - title: Example
    cards:
      - type: custom:softphone-card
        name: Jadson Santos
        username: 4001
        password: 4001
        sipServer: 192.168.0.33
        wss: wss://192.168.0.33:8089/ws